name: Scrape Google and Save Data

on:
  push:
    branches:
      - main  # Adjust this to match your default branch

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Adjust this to your preferred Python version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Scrape and save
        run: python scrape.py  # Change the path to your scraping script

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add scraped data"
          git push
